var levelsCollection = {
    level1: [
            'x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            'x         !                         x',
            'x                 o                 x',
            'x         o                         x',
            'x                                   x',
            'x     0   !    x!!!!!    1          x',
            'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xx',
            'x      o     o       x              x',
            'x                    x              x',
            'x         x                         x',
            'x         x     x   ox       o      x',
            'xo   2   xx  !  x3  !x!    o 4 o    x',
            'xx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            'x      o  o  o  o  o  o  o     x    x',
            'x                                   x',
            'x                     6             x',
            'x5     x  x  x  x  x  x  x  x       x',
            'xxxxx!!x!!x!!x!!x!!x!!x!!x!!x!!     x',
            'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!   !!',
            'x                              !    !',
            'x         x             x           !',
            'd    o    x  x        x x           !!',
            'd   ooo   x  x       xx xx     !    !!',
            'd 7ooooo8 x!!x!!xo!!xx!9!xx    !!x!!!!',
            'xxxxxxxxxxx!!x!xxxx!xxxxxxxxxxx!!x!!!!',
            '              !    !            !  !!!',
            '                                    !!',
            '           !!      !               ! !',
            '            !      !            !    !',
        ]
}

